name: Run Unit Tests

on: [push]

jobs:
  run-api-solid-unit-tests:
    name: Run Api Solid Unit Tests
    runs-on: ubuntu-latest

    steps:
      - run: cd 03-api-solid
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci
      - run: npm run test
      