name: Run Unit Tests

on:
  push:
    branches:
      - main

jobs:
  run-api-solid-unit-tests:
    name: Run Api Solid Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Navigate to API Solid folder project
        run: cd 03-api-solid/

      - name: LS
        run: ls
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm run test
      